title = "HardPy with Auth Example"
tests_name = "Authorization Example"

[database]
storage_type = "couchdb"
user = "dev"
password = "dev"
host = "localhost"
port = 5984

[frontend]
host = "localhost"
port = 8000
language = "en"

[auth]
required = true
adapter = "conftest.CustomAuthAdapter"
session_timeout = 60  # 60 minutes session timeout
